# configs/bernoulli.yaml
output_dir: "experiments/bernoulli"

model:
  n_positions: 60          # Total positions in sequence
  d_model: 256             # Embedding dimension
  n_layer: 12              # Number of transformer layers  
  n_head: 8                # Number of attention heads
  kernel_type: "softmax"   # Type of kernel (transformer or softmax)

task:
  name: "bernoulli"        # Distribution name

training:
  batch_size: 64
  n_batches: 1000
  n_epochs: 20
  learning_rate: 0.003
  save_every: 500
  eval_every: 100
  seed: 42
  patience: 30
  train_steps: 20000
  warmup_steps: 500
  steps_per_epoch: 100
  n_val_tasks: 5
  n_test_tasks: 2
  grad_clip: 1.0
  weight_decay: 0.01
  keep_every_steps: 5000   # Save model snapshot every this many steps

  # Curriculum learning parameters
  min_points: 10           # Start with this many points 
  min_dims: 2              # Start with this many dimensions
  point_schedule: 0.6      # Reach max points after 60% of training
  dim_schedule: 0.8        # Reach max dimensions after 80% of training

logging:
  use_wandb: false
  project_name: "prob-icl"
  log_every: 100 