# configs/gaussian.yaml
output_dir: "experiments/gaussian"

model:
  n_dims: 2                # Input feature dimension
  n_positions: 60          # Total positions in sequence
  n_embd: 256              # Embedding dimension
  n_layer: 12              # Number of transformer layers  
  n_head: 8                # Number of attention heads

task:
  name: "gaussian"
  task_scale: 0.25         # Scale parameter for Gaussian distribution

train:
  batch_size: 64
  n_batches: 1000
  n_epochs: 20
  lr: 0.003
  save_every: 500
  eval_every: 100
  seed: 42
  patience: 30
  train_steps: 20000
  warmup_steps: 500

logging:
  use_wandb: false
  project_name: prob-icl
  log_every: 100 