# configs/linear.yaml
output_dir: "experiments/linear"

model:
  model_type: "gpt2"
  n_layer: 12
  n_positions: 41
  n_dims: 10
  d_model: 256
  n_heads: 8

task:
  name: "linear"
  task_scale: 0.25

training:
  batch_size: 64
  train_steps: 1000
  learning_rate: 0.001
  grad_clip: 1.0
  save_every: 100
  eval_every: 50
  n_val_tasks: 5
  
  # Curriculum learning parameters (only for dimensions)
  min_dims: 10
  dim_schedule: 0
  
  # Point settings
  min_points: 41           # Same as n_positions
  point_schedule: 0        # Disable point curriculum
  
  # Optional settings for task pools/seeds
  num_unique_distributions: 10000
  pool_size: 1000

logging:
  use_wandb: false
  project_name: "prob-icl"
  log_every: 50 